In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen, Request

In [2]:
all_teams = ['ATL','BRK','BOS','CHO','CHI','CLE','DAL','DEN','DET','GSW','HOU','IND','LAC','LAL','MEM','MIA','MIL','MIN',
        'NOP','NYK','OKC','ORL','PHI','PHO','POR','SAC','SAS','TOR','UTA','WAS']
name, pos, teams = [], [], []

In [3]:
def scrape_positions(team):
    res = requests.get('https://www.basketball-reference.com/teams/{0}/2020.html'.format(team))
    soup = BeautifulSoup(res.text, 'lxml')
    table = soup.find('table', attrs={'id':'roster'})
    for tr in table.find_all('tr'):
        name_td = tr.find('td', attrs={'data-stat':'player'})
        pos_td = tr.find('td', attrs={'data-stat':'pos'})
        if name_td is not None:
            name.append(name_td.get('csk'))
            pos.append(pos_td.text)
            teams.append(team)

In [4]:
for team in all_teams:
    scrape_positions(team)

In [5]:
df = pd.DataFrame({'player name':name, 'team':teams, 'position':pos})
df.to_csv('./../OutputCSVs/all_player_positions.csv', header=True, index=False)

In [6]:
df

            player name team position
0       Hunter,De'Andre  ATL       SF
1            Young,Trae  ATL       PG
2          Carter,Vince  ATL       SF
3           Reddish,Cam  ATL       SF
4         Huerter,Kevin  ATL       SG
..                  ...  ...      ...
508      Napier,Shabazz  WAS       PG
509     Robinson,Jerome  WAS       SG
510  Williams,Johnathan  WAS        C
511           Wall,John  WAS        G
512        Grant,Jerian  WAS        G

[513 rows x 3 columns]

In [7]:
df['position'].unique()

array(['SF', 'PG', 'SG', 'C', 'PF', 'F', 'F-G', 'G', 'G-F', 'F-C'],
      dtype=object)

In [8]:
odd_positions = ['F','F-G','G','G-F','F-C']
df[df['position'].isin(odd_positions)]

             player name team position
15       Labissière,Skal  ATL        F
31            Hall,Donta  BRK        F
32          Durant,Kevin  BRK      F-G
33         Johnson,Tyler  BRK        G
34        Crawford,Jamal  BRK        G
35       Beasley,Michael  BRK        F
67          Simmons,Kobi  CHO        G
68          Spalding,Ray  CHO        F
100  Pointer,Sir'Dominic  CLE      G-F
101          Mac,Sheldon  CLE        G
102        Windler,Dylan  CLE      G-F
103          Bell,Jordan  CLE        F
121           Burke,Trey  DAL        G
138           Cook,Tyler  DEN        F
170        Thompson,Klay  GSW      G-F
187          Nwaba,David  HOU        G
188     Mbah a Moute,Luc  HOU        F
238       Cacok,Devontae  LAL        F
239         Waiters,Dion  LAL        G
240           Smith,J.R.  LAL      G-F
256      Winslow,Justise  MEM        F
257        Porter,Jontay  MEM      F-C
274       Alexander,Kyle  MIA        F
291     Reynolds,Cameron  MIL        G
306          Turner,Evan  MIN        G
307       Spellman,Omari  MIN        F
324        Miller,Darius  NOP        F
325  Thornwell,Sindarius  NOP        G
340          Pinson,Theo  NYK        G
341         Wooten,Kenny  NYK        F
342         Harper,Jared  NYK        G
359       Roberson,Andre  OKC      G-F
393       Broekhoff,Ryan  PHI        F
409        Payne,Cameron  PHO        G
426         Adams,Jaylen  POR        G
443         Brewer,Corey  SAC      F-G
460         Zeller,Tyler  SAS      F-C
511            Wall,John  WAS        G
512         Grant,Jerian  WAS        G